my-properties:
  property:
    crossOrigin: "http://localhost:3000"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_crud?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
